package constants

func GeneratePlayerList() []string {
	return []string{
		"Lionel Messi",
		"Cristiano Ronaldo",
		"Neymar Jr.",
		"Kylian Mbappé",
		"Robert Lewandowski",
		"Mohamed Salah",
		"Kevin De Bruyne",
		"Virgil van Dijk",
		"Erling Haaland",
		"Karim Benzema",
		"Zlatan Ibrahimović",
		"Gareth Bale",
		"Luka Modrić",
		"Sergio Ramos",
		"Manuel Neuer",
		"Harry Kane",
		"Toni Kroos",
		"Sadio Mané",
		"Paul Pogba",
		"Antoine Griezmann",
		"Eden Hazard",
		"Raheem Sterling",
		"Joshua Kimmich",
		"Jan Oblak",
		"Alisson Becker",
		"Ederson",
		"Riyad Mahrez",
		"Son Heung-min",
		"Romelu Lukaku",
		"Bruno Fernandes",
		"Frenkie de Jong",
		"Marquinhos",
		"Kalvin Phillips",
		"Phil Foden",
		"Jadon Sancho",
		"Marcus Rashford",
		"Trent Alexander-Arnold",
		"Andrew Robertson",
		"Thiago Alcântara",
		"Gerard Piqué",
		"Sergio Agüero",
		"Luis Suárez",
		"Ángel Di María",
		"N'Golo Kanté",
		"Gianluigi Buffon",
		"Andrea Pirlo",
		"Xabi Alonso",
		"Andrés Iniesta",
		"Xavi Hernández",
		"David Beckham",
		"Ronaldinho",
		"Thierry Henry",
		"Didier Drogba",
		"Steven Gerrard",
	}
}
